fix: Use specific providers instead of commonMain optimal for cryptography-kotlin
Use specific providers instead of commonMain optimal for cryptography-kotlin to fix "ld: symbol(s) not found for architecture arm64" build error.

* https://github.com/whyoleg/cryptography-kotlin/issues/52

Bug: #85
Change-Id: Ife96abe50285721996eb1f21da6d764c90eeb92c